# Generated by Django 4.1 on 2022-08-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='membershipcode',
            field=models.CharField(default='FREE', max_length=5),
        ),
    ]
