# Generated by Django 4.1 on 2022-08-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_customuser_managers_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userstatus',
            field=models.CharField(default='student', max_length=10),
        ),
    ]
