# Generated by Django 4.1 on 2022-08-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
