# Generated by Django 4.1 on 2022-08-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_customuser_isadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='userstatus',
            new_name='status',
        ),
    ]
