# Generated by Django 4.1 on 2022-08-23 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courtname', models.CharField(max_length=30)),
                ('courtlocation', models.CharField(max_length=60)),
                ('membership_req', models.CharField(max_length=5)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='sports.sports')),
            ],
        ),
    ]
