# Generated by Django 4.1 on 2022-08-26 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_rename_sportid_sports_sportcode'),
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='sports.sports'),
        ),
    ]
