# Generated by Django 4.1 on 2022-09-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_alter_courts_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='courtname',
            field=models.CharField(max_length=12),
        ),
    ]
