# Generated by Django 4.1 on 2022-08-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sports',
            old_name='sportid',
            new_name='sportcode',
        ),
    ]
