# Generated by Django 4.1 on 2022-08-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='waitlist',
            field=models.IntegerField(null=True),
        ),
    ]
