# Generated by Django 4.1 on 2022-08-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_waitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='waitlist',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
