# Generated by Django 4.1 on 2022-08-26 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_alter_courts_sport'),
        ('sports', '0002_rename_sportid_sports_sportcode'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='courts.courts'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sportid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='sports.sports'),
        ),
    ]
