# Generated by Django 4.1 on 2022-08-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_court_alter_inventory_sportid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
