# Generated by Django 4.1 on 2022-08-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='sportid',
            new_name='sport',
        ),
    ]
