# Generated by Django 4.1 on 2022-08-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_rename_sportid_sports_sportcode'),
        ('inventory', '0004_rename_sportid_inventory_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='itemname',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='sport',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='sports.sports')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.item'),
        ),
    ]
