# Generated by Django 4.1 on 2022-08-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_inventory_itemname_remove_inventory_sport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='itemname',
        ),
    ]
